Skjema
navikt/analytics-taxonomy pull request #4
Opened 2020-09-16 15:40 UTC by tobiasmcvey

Forslag til å definere spore utfylling og innsending av skjemaer i felles taksonomi.

Inneholder 

- [ ] Skjema åpnet
- [ ] Skjema startet
- [ ] Skjema spørsmål besvart
- [ ] Skjema steg fullført
- [ ] Skjema validering feilet
- [ ] Skjema innsending feilet
- [ ] Skjema fullført

Kan du lese over @mijohansen og kommentere med forbedringer og din vurdering?

2020-09-21 07:41 UTC, mijohansen requested changes
Tror vi skal kjøre dette med korrekt orddeling... altså skjemasteg fullført. osv.

2020-09-22 12:03 UTC, zrrrzzt commented
Vil det være aktuelt for noen noen skjema å mellomlagre?
I så fall bør "Skjema utfylling pauset" og "Skjema utfylling gjenopptatt" kanskje inn.

2020-09-23 07:35 UTC, tobiasmcvey commented
> Vil det være aktuelt for noen noen skjema å mellomlagre?
> I så fall bør "Skjema utfylling pauset" og "Skjema utfylling gjenopptatt" kanskje inn.

@zrrrzzt veldig gode forslag. Tenker at det kan være relevant å logge **når** man sluttet og **når** man begynte å fylle ut igjen? I tilfelle det er snakk om timer eller dager her.

2020-09-23 08:34 UTC, zrrrzzt commented
Ja. Tidspunkt er aktuelt i begge tilfeller 👍

2020-09-23 14:36 UTC, mijohansen commented
> Ja. Tidspunkt er aktuelt i begge tilfeller 👍

Hva om å isteden logge tid brukt for å fylle it skjemaet i antall minutter? Langt enklere å jobbe med en metric enn ett tidspunkt. Jeg pleier aldri å sende tidspunkt annet enn event-tidspunktet til ett api.

Ta eksemplet `Kinobillett bestillt`, da ønsker du deg følgende attributter:
- pris
- ukedag for forestilling
- antall dager til forestilling
- navn på forestilling
- antall billetter bestilt
- antall billetter ledig

Det vil være fristende å legge med feks ID på den aktuelle forestillingen og tidspunkt. Men da ville man måtte inn i andre datakilder for å kunne lage statistikker. Evt. ville man måtte regne på datoene for å kunne få ut noe fornuftig.

2020-09-23 16:27 UTC, zrrrzzt commented
Enig i innspillet om å få inn tid brukt som en metrikk fordi det vil gjøre det enklere å sammenligne og jeg synes det er interessant å vite hvor lang tid man bruker på utfylling. Jeg ønsker fortsatt å vite om det er tatt pauser eller ei, men det kan funke å ha "Skjemautfylling gjenopptatt" og så sende inn hvor lang pause man har tatt. Med fare for at det blir mange minutter om pausen varer i flere dager :-)

2020-10-27 12:35 UTC, merged